#!/bin/sh
sudo exec > /tmp/vase.txt 2>&1
echo $(date)
echo "running sclang postbootscript..."
echo "starting jack..."
jackd -dalsa -dhw:1,0 -p512 -n3 -s &
sleep 4
each "start supercollider..."
sclang /home/debian/vase/vase.scd &
sleep 4
echo "starting python..."
sudo python /home/debian/vase/vase.py
